name: Firebase App Distribution Debug

on: workflow_dispatch

jobs:
  app_distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          ssh-key: ${{ secrets.SSH_KEY }}
          submodules: 'recursive'
          ref:  ${{ github.head_ref }}

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Apk
        id: buildApk
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleDebug
